# vi: ft=ruby

$provision = <<-SCRIPT
# https://docs.docker.com/install/linux/docker-ce/centos/
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install -y docker-ce-18.06.1.ce
sed -i /usr/lib/systemd/system/docker.service 's!ExecStart=/usr/bin/dockerd!ExecStart=/usr/bin/dockerd --exec-opt native.cgroupdriver=cgroupfs!'
systemctl enable docker
systemctl start docker

# https://kubernetes.io/docs/tasks/tools/install-kubectl/
cat <<EOF > /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
yum install -y kubectl

# https://kubernetes.io/docs/tasks/tools/install-minikube/
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube \
  && install minikube /usr/bin/

yum install -y socat
sysctl -w net.bridge.bridge-nf-call-iptables=1
swapoff -a
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.define "minikube" do |c|
    c.vm.hostname = "minikube"
    c.vm.box = "centos/7"
    c.vm.provision "shell", inline: $provision
    c.vm.network "private_network", ip: "192.168.30.2"
    c.vm.provider "virtualbox" do |v|
      v.cpus = 2
      v.memory = 1024
    end
  end
end
